services:
  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=R00Tpa$$w0rd
      - MYSQL_DATABASE=todo-list
      - MYSQL_USER=user
      - MYSQL_PASSWORD=MegaTajneHaslo
    volumes:
      - ./db:/config
    ports:
       - 3306:3306
    restart: unless-stopped
