services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: R00Tpa$$w0rd
      MYSQL_DATABASE: todo-list
    ports:
      - "1234:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    restart: unless-stopped
